language: bash

sudo: required
dist: trusty

#addons:
#  apt:
#    packages:
#      - oracle-java8-installer

#jdk: oraclejdk8
#https://github.com/travis-ci/travis-ci/issues/6371
#before_install:
#  - jdk_switcher use oraclejdk8

install:
#  - sudo apt-get install oracle-java8-set-default

  - sudo apt-get install -y python-software-properties
  - sudo add-apt-repository -y ppa:webupd8team/java
  - sudo apt-get update
  - sudo apt-get install -y oracle-java8-installer
  - sudo apt-get install -y curl unzip zip wget

  ## install sdkman (see http://sdkman.io/install.html)
  - bash -c "curl -s "https://get.sdkman.io" | bash"
  - source "/home/travis/.sdkman/bin/sdkman-init.sh"

  ## install kotlin and maven
  - sdk install maven
  - sdk install kotlin

  ## install assert.h
  - wget https://raw.github.com/lehmannro/assert.sh/v1.1/assert.sh && chmod +x assert.sh

  - export KSCRIPT_HOME="/home/travis/build/holgerbrandl/kscript"
  - pwd
  - export PATH=$KSCRIPT_HOME::$PATH

  - which kscript
  - which expandcp.kts
  - which assert.sh

  ## does it run outside of test-suite?
  - kscript --help
  - kscript ${KSCRIPT_HOME}/test/resources/multi_line_deps.kts

script: ./test/test_suite.sh

